### ISSUE TITLE
Colors are lost

### ISSUE THREAD

**Issue by danielo515** [alexlafroscia/dotfiles#3]
Hello @alexlafroscia 

Sorry for bothering you on your personal dotfiles repository. I just have installed your dot files and they are great.
However, there is one small detail: I totally lost my colors on iterm2. At first I thought it was about the zsh theme, but then I changed it and the colors remain plain.
Do you have any idea about what could have happened ?

 another suggestion (if you want to take it). Since you have a great installer which has some interactive questions, it would be nice if the installer do not overwrites critical files like bashrc and zshrc.

Thanks and regards.

**Comment by danielo515** [comment]
Sorry, it was my fault. It was the minimum color contrast configuration on iterm.
THANKS

https://superuser.com/a/694642/420282

**Comment by alexlafroscia** [comment]
Cool, glad you find them useful! 

RE: the suggestion: That's probably a good idea, but it's also more for my person use where I _want_ to override the original file. I've actually been working (slowly) on a much better installation script setup, so that's something I'll keep in mind as I build that out!

**Comment by alexlafroscia** [comment]
Just to make sure before closing, was your color issue resolved?

**Comment by danielo515** [comment]
Yes, absolutely. Thanks you very much for taking my suggestions in account and sorry for leaving the issue open.

Regards
